# Default values for trembita-1-22-6-ss.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# This will set the replicaset count more information can be found here: https://kubernetes.io/docs/concepts/workloads/controllers/replicaset/
replicaCount: 1

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: kshypachov/trembita_ss_v1.22.7
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.0-WCC-WMLA-WP-WIDPRA-WOC-WVRA-WREST"

# This is for the secrets for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

cloudPostgresDatabase:
  enabled: true

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: {}
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

# This is for setting up a service more information can be found here: https://kubernetes.io/docs/concepts/services-networking/service/
services: []


resources: {}

# This is to setup the liveness and readiness probes more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
livenessProbe: []
#  httpGet:
#    path: /
#    port: http
readinessProbe: []
#  httpGet:
#    path: /
#    port: http

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []

# Additional volumeMounts on the output Deployment definition.
volumeMounts: {}
#  - name: db-config
#    mountPath: /etc/uxp/db.properties
#    subPath: db.properties

nodeSelector: {}

tolerations: []

affinity: {}

configMap: {}
#  name: uxp-db-config


postgresql_init:
  initJob:
    containerImageName: kshypachov/trembita_ss_v1.22.6-pg-init
    containerImageVer: v1.0.8
    env:
#      - name: PGHOST
#        value: uxp-postgres
      - name: PGPORT
        value: 5432
      - name: PGROOT_USER
        value: postgres
      - name: PGROOT_PASSWORD
        value: mysecretpassword
      - name: SERVERCONF_DB_USER
        value: serverconf
      - name: SERVERCONF_DB_PASS
        value: serverconfp
      - name: MESSAGELOG_DB_USER
        value: messagelog
      - name: MESSAGELOG_DB_PASS
        value: messagelogp
      - name: IDENTITY_DB_USER
        value: identityprovider
      - name: IDENTITY_DB_PASS
        value: identityproviderp
      - name: OPMONITOR_DB_USER
        value: opmonitor
      - name: OPMONITOR_DB_PASS
        value: opmonitorp
      - name: OPMONITOR_ADMIN_DB_USER
        value: opmonitor_admin
      - name: OPMONITOR_ADMIN_DB_PASS
        value: opmonitor_adminp

postgresql:
  containerName: postgres
  image: postgres:16
  username: postgres
  password: mysecretpassword
  database: appdb
  port: 5432
  max_connections: 200

  persistence:
    enabled: true
    size: 1Gi
    storageClass: ""

  env:
    - name: PGDATA
      value: /var/lib/postgresql/data/pgdata
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: mysecretpassword
    - name: POSTGRES_DB
      value: appdb



trembita_config:
  ss_to_db_access:
    PGPORT: 5432
    PGROOT_USER: postgres
    PGROOT_PASSWORD: mysecretpassword
    SERVERCONF_DB_USER: serverconf
    SERVERCONF_DB_PASS: serverconfp
    MESSAGELOG_DB_USER: messagelog
    MESSAGELOG_DB_PASS: messagelogp
    IDENTITY_DB_USER: identityprovider
    IDENTITY_DB_PASS: identityproviderp
    OPMONITOR_DB_USER: opmonitor
    OPMONITOR_DB_PASS: opmonitorp
    OPMONITOR_ADMIN_DB_USER: opmonitor_admin
    PMONITOR_ADMIN_DB_PASS: opmonitor_adminp


  internal_api_access:
    service:
      enabled: true
      type: ClusterIP
      selectors:
        trembita.io/internalport: tcp80
      port: 80
      portName: uxp-internal

    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: api.trembita2.remote
          paths:
          - path: /
            pathType: Prefix
            port: 80

  external_api_access:
    service:
      enabled: true
      type: LoadBalancer
      selectors:
        trembita.io/externalport: tcp5500
      port: 5500
      portName: uxp-external


  web_ui_access:
    service:
      enabled: true
      type: ClusterIP
      selectors:
        trembita.io/webport: tcp4000
      port: 4000
      portName: uxp-web


    ingress:
      enabled: true
      className: "nginx"
      hosts:
        - host: trembita2.remote
          paths:
          - path: /
            pathType: Prefix
            port: 4000

      tls:
        - hosts:
            - trembita2.remote
          secretName: trembita-tls


  configMaps:
    enabled: true  # Disable all configmaps and related mountpoints. If all configmaps disabled - need to set @ false @ there
    db_properties: # For testing only!!!!!! ConfigMap not suitable for storing sensitive data like a DB password
      enabled: true
      name: db-properties
      mountPath: /etc/uxp/db.properties
      subPath: db.properties

    local_ini:
      enabled: true
      name: local-ini
      mountPath: /etc/uxp/conf.d/local.ini
      subPath: local.ini

    default_uxp:
      enabled: true
      name: default-uxp
      mountPath: /etc/nginx/sites-enabled/default-uxp
      subPath: default-uxp

    uxp_identity_provider_rest_api:
      enabled: true
      name: uxp-identity-provider-rest-api
      mountPath: /etc/nginx/conf.d/uxp-identity-provider-rest-api-location.include
      subPath: uxp-identity-provider-rest-api-location.include

    uxp_securityserver_rest_api:
      enabled: true
      name: uxp-securityserver-rest-api
      mountPath: /etc/nginx/conf.d/uxp-securityserver-rest-api-location.include
      subPath: uxp-securityserver-rest-api-location.include

    tokens_autologin:
      enabled: true
      name: tokens-autologin
      mountPath: /usr/share/uxp/bin/tokens-autologin.py
      subPath: tokens-autologin.py

    conf_client_logback:
      enabled: true
      name: conf-client-logback
      mountPath: /etc/uxp/conf.d/confclient-logback.xml
      subPath: confclient-logback.xml

    message_log_archiver_logback:
      enabled: true
      name: message-log-archiver-logback
      mountPath: /etc/uxp/conf.d/messagelog-archiver-logback.xml
      subPath: messagelog-archiver-logback.xml

    identity_provider_rest_api_logback:
      enabled: true
      name: identity-provider-rest-api-logback
      mountPath: /etc/uxp/conf.d/identity-provider-rest-api-logback.xml
      subPath: identity-provider-rest-api-logback.xml

    ocsp_cache_logback:
      enabled: true
      name: ocsp-cache-logback
      mountPath: /etc/uxp/conf.d/ocsp-cache-logback.xml
      subPath: ocsp-cache-logback.xml

    verifier_logback:
      enabled: true
      name: verifier
      mountPath: /etc/uxp/conf.d/verifier-rest-api-logback.xml
      subPath: verifier-rest-api-logback

    seg_rest_api:
      enabled: true
      name: seg-rest-api
      mountPath: /etc/uxp/conf.d/securityserver-rest-api-logback.xml
      subPath: securityserver-rest-api-logback.xml

    proxy_logback:
      enabled: true
      name: proxy-logback
      mountPath: /etc/uxp/conf.d/proxy-logback.xml
      subPath: proxy-logback.xml

  trembita_main_app_container_tags:
    enabled: true
    tags:
      app.kubernetes.io/component: trembita
      trembita.io/webport: tcp4000
      trembita.io/internalport: tcp80
      trembita.io/externalport: tcp5500

  trembita_workers_tags:
    enabled: true
    tags:
      app.kubernetes.io/component: trembita
#      trembita.io/webport: tcp4000
      trembita.io/internalport: tcp80
      trembita.io/externalport: tcp5500

  trembita_worker_pods:
    enabled: true
    image: kshypachov/trembita_ss_v1.22.7:v1.0.0-WCC-WMLA-WP-WIDPRA-WOC-WVRA
    autoscaling:
      enabled: true
      min: 1
      max: 2
      cpuUtilization: 80
    secrets:
      auto-login:
        enabled: true
        mountpoint: /run/secrets/trembita.io/autologin.secret.json
        filename: autologin.json.secret
        values:
          USERNAME: "token-login"
          PASSWORD: "123456789012"
          REDIRECT_URI: "https://trembita2.remote"
          CLIENT_ID: "uxp-ss-ui"
          SECURITY_SERVER_ADDRESS: "http://127.0.0.1:4000"
          TOKEN_CREDENTIALS: "0:1234"
          OAUTH_RETRIES: "3"
    lifecycle: {}
#      postStart:
#        exec:
#          command:
#            - /bin/sh
#            - -c
#            - |
#              python3 /usr/share/uxp/bin/tokens-autologin.py
    env:
      TZ: Europe/Kyiv

  trembita_main_app_pod:
    env:
      TZ: Europe/Kyiv

  trembita_configuration_client_pod:  # settins specific for configuration client component
    name: conf-client
    image: kshypachov/trembita_configuration_client_1.12.7:v1.0.5
    env:
      TZ: Europe/Kyiv

  trembita_message_log_archiver_pod:  # settins specific for configuration client component
    name: message-log
    image: kshypachov/trembita_message_log_archiver_1.12.7:v1.0.2
    env:
      TZ: Europe/Kyiv

  trembita_identity_provider_rest_api_pod: # settins specific for configuration client component
    name: identity-rest-api
    image: kshypachov/trembita_identity_provider_rest_api_1.22.7:v1.0.1
    env:
      TZ: Europe/Kyiv

  trembita_ocsp_cache_pod:
    name: ocsp-cache
    image: kshypachov/trembita_ocsp_cahce_1.22.7:v1.0.1
    env:
      TZ: Europe/Kyiv
    ephemeralVolumeRAM:
      - name: ocsp-cache # volume in tmpfs for store ocsp answers
        mountPath: /var/cache/uxp
        sizeLimit: "100Mi"

  trembita_verifier_pod:
    name: verifier
    image: kshypachov/trembita_verifier_v1.22.7:v1.0.0
    env:
      TZ: Europe/Kyiv

  trembita_seg_rest_api_pod:
    name: seg-rest-api
    image: kshypachov/trembita_seg_rest_api_v1.22.7:v1.0.0
    env:
      TZ: Europe/Kyiv

  trembita_proxy_pod:
    name: proxy
    image: kshypachov/trembita_proxy_v1.22.7:v1.0.5
    env:
      TZ: Europe/Kyiv



  sharedVolumes: # volumes which will connect to all trembita pods in this chart. Data will copy from original image (entire tembita server) during init phase
    etc-uxp:
      enabled: true
      initCopy: false
      size: 100Mi
      mountPath: /etc/uxp
      storageClassName: "longhorn-rwx"
      accessModes:
        - ReadWriteMany

    usr-share-uxp:
      enabled: true
      initCopy: false
      size: 1.5Gi
      mountPath: /usr/share/uxp/
      storageClassName: "longhorn-rwx"
      accessModes:
        - ReadWriteMany

    var-lib-uxp:
      enabled: true
      initCopy: false
      size: 15Gi
      mountPath: /var/lib/uxp/
      storageClassName: "longhorn-rwx"
      accessModes:
        - ReadWriteMany



minio:
#  nameOverride: "minio"
  fullnameOverride: minio
  auth:
    rootUser: minioadmin
    rootPassword: minioadmin
  defaultBuckets: uxp-messagelog
  mode: standalone
  persistence:
    enabled: true
    size: 1Gi
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: minio.trembita.office

  apiIngress:
    enabled: true
    ingressClassName: "nginx"
    hostname: api.minio.trembita.office

vector:
  role: Aggregator
  fullnameOverride: vector
  defaultConfig:
    enabled: false

  customConfig:
    data_dir: /vector-data-dir
    sources:
      http_input:
        type: http_server
        address: 0.0.0.0:2080

    sinks:
      null_sink:
        type: file
        inputs: [ http_input ]
        path: "/dev/null"
        encoding:
          codec: json
