--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: messagelog
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO messagelog;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: messagelog
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO messagelog;

--
-- Name: metadata; Type: TABLE; Schema: public; Owner: messagelog
--

CREATE TABLE public.metadata (
    id bigint NOT NULL,
    transactionid character varying(255) NOT NULL,
    response boolean NOT NULL,
    clientside boolean NOT NULL,
    queryid character varying(255),
    userid character varying(255),
    protocolversion character varying(255),
    clientinstancecode character varying(255) NOT NULL,
    clientmemberclass character varying(255) NOT NULL,
    clientmembercode character varying(255) NOT NULL,
    clientsubsystemcode character varying(255),
    serviceinstancecode character varying(255) NOT NULL,
    servicememberclass character varying(255) NOT NULL,
    servicemembercode character varying(255) NOT NULL,
    servicesubsystemcode character varying(255),
    servicecode character varying(255) NOT NULL,
    serviceversion character varying(255),
    timestampid character varying(255),
    archiveid character varying(255),
    createddate timestamp without time zone NOT NULL,
    status character varying(255) DEFAULT 'NEW'::character varying NOT NULL,
    issue character varying(255)
);


ALTER TABLE public.metadata OWNER TO messagelog;

--
-- Name: metadata_id_seq; Type: SEQUENCE; Schema: public; Owner: messagelog
--

ALTER TABLE public.metadata ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.metadata_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: messagelog
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
0-initial	Cybernetica AS	messagelog-metadata/0-initial.xml	2025-05-10 15:49:02.67864	1	EXECUTED	9:7cd338e968e9ed5ba9e160d0bd18a862	createTable tableName=metadata; addUniqueConstraint constraintName=transactionid_response_clientside_uk, tableName=metadata		\N	4.29.2	\N	\N	6892142608
1-indices	Cybernetica AS	messagelog-metadata/1-indices.xml	2025-05-10 15:49:02.702462	2	EXECUTED	9:289876f485342a2e75fa78a22af841a3	createIndex indexName=metadata_createddate_idx, tableName=metadata; createIndex indexName=metadata_transactionid_response_clientside_idx, tableName=metadata; createIndex indexName=metadata_timestampid_archiveid_idx, tableName=metadata		\N	4.29.2	\N	\N	6892142608
2-status	Cybernetica AS	messagelog-metadata/2-status.xml	2025-05-10 15:49:02.723553	3	EXECUTED	9:fa7855d854dc96007e58af8406763fab	addColumn tableName=metadata; sql		\N	4.29.2	\N	\N	6892142608
3-issue	Cybernetica AS	messagelog-metadata/3-issue.xml	2025-05-10 15:49:02.732843	4	EXECUTED	9:91a1edbf68098acd9152992eedf7a752	addColumn tableName=metadata		\N	4.29.2	\N	\N	6892142608
4-drop-indices	Cybernetica AS	messagelog-metadata/4-drop-indices.xml	2025-05-10 15:49:02.746091	5	EXECUTED	9:a3dab315fadc0091f9ddbb1143edf2d4	dropIndex indexName=metadata_createddate_idx, tableName=metadata; dropIndex indexName=metadata_transactionid_response_clientside_idx, tableName=metadata; dropIndex indexName=metadata_timestampid_archiveid_idx, tableName=metadata		\N	4.29.2	\N	\N	6892142608
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: messagelog
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: metadata; Type: TABLE DATA; Schema: public; Owner: messagelog
--

COPY public.metadata (id, transactionid, response, clientside, queryid, userid, protocolversion, clientinstancecode, clientmemberclass, clientmembercode, clientsubsystemcode, serviceinstancecode, servicememberclass, servicemembercode, servicesubsystemcode, servicecode, serviceversion, timestampid, archiveid, createddate, status, issue) FROM stdin;
\.


--
-- Name: metadata_id_seq; Type: SEQUENCE SET; Schema: public; Owner: messagelog
--

SELECT pg_catalog.setval('public.metadata_id_seq', 1, false);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: messagelog
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: metadata metadata_pk; Type: CONSTRAINT; Schema: public; Owner: messagelog
--

ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT metadata_pk PRIMARY KEY (id);


--
-- Name: metadata transactionid_response_clientside_uk; Type: CONSTRAINT; Schema: public; Owner: messagelog
--

ALTER TABLE ONLY public.metadata
    ADD CONSTRAINT transactionid_response_clientside_uk UNIQUE (transactionid, response, clientside);


--
-- PostgreSQL database dump complete
--

