--
-- PostgreSQL database dump
--

-- Dumped from database version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.8 (Ubuntu 16.8-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: hstore; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS hstore WITH SCHEMA public;


--
-- Name: EXTENSION hstore; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION hstore IS 'data type for storing sets of (key, value) pairs';


--
-- Name: read_file(text); Type: FUNCTION; Schema: public; Owner: serverconf
--

CREATE FUNCTION public.read_file(file text) RETURNS text
    LANGUAGE plpgsql
    AS $$
    DECLARE
      content text;
      tmp text;
    BEGIN
      file := quote_literal(file);
      tmp := quote_ident('xml_data');

      EXECUTE 'CREATE TEMP TABLE ' || tmp || ' (content text)';
      EXECUTE 'COPY ' || tmp || ' FROM ' || file;
      EXECUTE 'SELECT string_agg(content, chr(10)) FROM ' || tmp INTO content;
      EXECUTE 'DROP TABLE ' || tmp;

      RETURN content;
    END;
  $$;


ALTER FUNCTION public.read_file(file text) OWNER TO serverconf;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accessright; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.accessright (
    id bigint NOT NULL,
    subjectid bigint NOT NULL,
    rightsgiven timestamp without time zone NOT NULL,
    acl_id bigint,
    servicecode character varying(255) NOT NULL,
    client_id bigint,
    path character varying(255),
    verbmask smallint
);


ALTER TABLE public.accessright OWNER TO serverconf;

--
-- Name: apikey; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.apikey (
    id bigint NOT NULL,
    hash character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    description character varying(255),
    addeddate timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.apikey OWNER TO serverconf;

--
-- Name: apikey_id_seq; Type: SEQUENCE; Schema: public; Owner: serverconf
--

ALTER TABLE public.apikey ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.apikey_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: certificate; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.certificate (
    id bigint NOT NULL,
    key_id bigint,
    alias character varying(255) NOT NULL,
    clientinstance character varying(255),
    clientclass character varying(255),
    clientcode character varying(255),
    clientsubsystem character varying(255),
    active boolean NOT NULL,
    status character varying(255) NOT NULL,
    data bytea NOT NULL
);


ALTER TABLE public.certificate OWNER TO serverconf;

--
-- Name: certificaterequest; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.certificaterequest (
    id bigint NOT NULL,
    key_id bigint,
    alias character varying(255) NOT NULL,
    clientinstance character varying(255),
    clientclass character varying(255),
    clientcode character varying(255),
    clientsubsystem character varying(255),
    subjectname text NOT NULL
);


ALTER TABLE public.certificaterequest OWNER TO serverconf;

--
-- Name: client; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.client (
    id bigint NOT NULL,
    conf_id bigint,
    identifier bigint,
    clientstatus character varying(255),
    isauthentication character varying(255)
);


ALTER TABLE public.client OWNER TO serverconf;

--
-- Name: clientcertificate; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.clientcertificate (
    id bigint NOT NULL,
    data bytea,
    client_id bigint
);


ALTER TABLE public.clientcertificate OWNER TO serverconf;

--
-- Name: databasechangelog; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.databasechangelog (
    id character varying(255) NOT NULL,
    author character varying(255) NOT NULL,
    filename character varying(255) NOT NULL,
    dateexecuted timestamp without time zone NOT NULL,
    orderexecuted integer NOT NULL,
    exectype character varying(10) NOT NULL,
    md5sum character varying(35),
    description character varying(255),
    comments character varying(255),
    tag character varying(255),
    liquibase character varying(20),
    contexts character varying(255),
    labels character varying(255),
    deployment_id character varying(10)
);


ALTER TABLE public.databasechangelog OWNER TO serverconf;

--
-- Name: databasechangeloglock; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.databasechangeloglock (
    id integer NOT NULL,
    locked boolean NOT NULL,
    lockgranted timestamp without time zone,
    lockedby character varying(255)
);


ALTER TABLE public.databasechangeloglock OWNER TO serverconf;

--
-- Name: device; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.device (
    id bigint NOT NULL,
    conf_id bigint,
    name character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    disabled boolean NOT NULL,
    batchsigningenabled boolean NOT NULL,
    configuration text NOT NULL,
    updateddate timestamp without time zone NOT NULL
);


ALTER TABLE public.device OWNER TO serverconf;

--
-- Name: endpoint; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.endpoint (
    id bigint NOT NULL,
    restapi_id bigint,
    path character varying(255) NOT NULL,
    generated boolean,
    addeddate timestamp without time zone
);


ALTER TABLE public.endpoint OWNER TO serverconf;

--
-- Name: groupmember; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.groupmember (
    id bigint NOT NULL,
    groupmemberid bigint NOT NULL,
    added timestamp without time zone NOT NULL,
    localgroup_id bigint
);


ALTER TABLE public.groupmember OWNER TO serverconf;

--
-- Name: hibernate_sequence; Type: SEQUENCE; Schema: public; Owner: serverconf
--

CREATE SEQUENCE public.hibernate_sequence
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.hibernate_sequence OWNER TO serverconf;

--
-- Name: httpheader; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.httpheader (
    id bigint NOT NULL,
    restapi_id bigint,
    service_id bigint,
    key character varying(255) NOT NULL,
    value text NOT NULL,
    action character varying(255) NOT NULL,
    CONSTRAINT cc_httpheader_onefk CHECK ((((restapi_id IS NOT NULL) OR (service_id IS NOT NULL)) AND ((restapi_id IS NULL) OR (service_id IS NULL))))
);


ALTER TABLE public.httpheader OWNER TO serverconf;

--
-- Name: identifier; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.identifier (
    id bigint NOT NULL,
    discriminator character varying(255) NOT NULL,
    type character varying(255),
    xroadinstance character varying(255),
    memberclass character varying(255),
    membercode character varying(255),
    subsystemcode character varying(255),
    serviceversion character varying(255),
    servicecode character varying(255),
    groupcode character varying(255),
    securitycategory character varying(255),
    servercode character varying(255)
);


ALTER TABLE public.identifier OWNER TO serverconf;

--
-- Name: importclientdiff; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.importclientdiff (
    id bigint NOT NULL,
    clientid bigint NOT NULL,
    missing boolean NOT NULL,
    importinfo_id bigint
);


ALTER TABLE public.importclientdiff OWNER TO serverconf;

--
-- Name: importinfo; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.importinfo (
    id bigint NOT NULL,
    version integer NOT NULL,
    exporteddate timestamp without time zone NOT NULL,
    securityserverid bigint NOT NULL,
    ip character varying(255) NOT NULL,
    hostname character varying(255) NOT NULL,
    missingclientaction character varying(255) NOT NULL,
    redundantclientaction character varying(255) NOT NULL,
    aborted boolean NOT NULL,
    importeddate timestamp without time zone NOT NULL,
    conf_id bigint
);


ALTER TABLE public.importinfo OWNER TO serverconf;

--
-- Name: key; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.key (
    id bigint NOT NULL,
    token_id bigint,
    alias character varying(255) NOT NULL,
    algorithm character varying(255) NOT NULL,
    publickey bytea NOT NULL,
    name character varying(255),
    type character varying(255)
);


ALTER TABLE public.key OWNER TO serverconf;

--
-- Name: localgroup; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.localgroup (
    id bigint NOT NULL,
    groupcode character varying(255) NOT NULL,
    description character varying(255) NOT NULL,
    updated timestamp without time zone NOT NULL,
    client_id bigint
);


ALTER TABLE public.localgroup OWNER TO serverconf;

--
-- Name: openapi; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.openapi (
    id bigint NOT NULL,
    restapi_id bigint NOT NULL,
    descriptionurl character varying(255) NOT NULL,
    refresheddate timestamp without time zone NOT NULL,
    content text
);


ALTER TABLE public.openapi OWNER TO serverconf;

--
-- Name: openapibaseurl; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.openapibaseurl (
    id bigint NOT NULL,
    openapi_id bigint,
    url character varying(255) NOT NULL
);


ALTER TABLE public.openapibaseurl OWNER TO serverconf;

--
-- Name: restapi; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.restapi (
    id bigint NOT NULL,
    client_id bigint,
    disabled boolean NOT NULL,
    disablednotice character varying(255),
    servicecode character varying(255) NOT NULL,
    serviceversion character varying(255),
    baseurl character varying(255) NOT NULL,
    sslauthentication boolean,
    timeout integer,
    addeddate timestamp without time zone
);


ALTER TABLE public.restapi OWNER TO serverconf;

--
-- Name: serverconf; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.serverconf (
    id bigint NOT NULL,
    servercode character varying(255),
    owner bigint
);


ALTER TABLE public.serverconf OWNER TO serverconf;

--
-- Name: service; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.service (
    id bigint NOT NULL,
    wsdl_id bigint,
    servicecode character varying(255) NOT NULL,
    serviceversion character varying(255),
    title character varying(255),
    url character varying(255),
    sslauthentication boolean,
    timeout integer,
    oneway boolean
);


ALTER TABLE public.service OWNER TO serverconf;

--
-- Name: service_securitycategories; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.service_securitycategories (
    service_id bigint NOT NULL,
    security_cat_id bigint NOT NULL,
    id bigint NOT NULL
);


ALTER TABLE public.service_securitycategories OWNER TO serverconf;

--
-- Name: service_securitycategories_id_seq; Type: SEQUENCE; Schema: public; Owner: serverconf
--

CREATE SEQUENCE public.service_securitycategories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.service_securitycategories_id_seq OWNER TO serverconf;

--
-- Name: service_securitycategories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: serverconf
--

ALTER SEQUENCE public.service_securitycategories_id_seq OWNED BY public.service_securitycategories.id;


--
-- Name: token; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.token (
    id bigint NOT NULL,
    conf_id bigint,
    alias character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    name character varying(255),
    device_id bigint,
    memberinstance character varying(255),
    memberclass character varying(255),
    membercode character varying(255)
);


ALTER TABLE public.token OWNER TO serverconf;

--
-- Name: tsp; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.tsp (
    id bigint NOT NULL,
    name character varying(255),
    url character varying(255) NOT NULL,
    conf_id bigint
);


ALTER TABLE public.tsp OWNER TO serverconf;

--
-- Name: uiuser; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.uiuser (
    id bigint NOT NULL,
    username character varying(255) NOT NULL,
    locale character varying(255)
);


ALTER TABLE public.uiuser OWNER TO serverconf;

--
-- Name: variable; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.variable (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    value character varying(255) NOT NULL
);


ALTER TABLE public.variable OWNER TO serverconf;

--
-- Name: wsdl; Type: TABLE; Schema: public; Owner: serverconf
--

CREATE TABLE public.wsdl (
    id bigint NOT NULL,
    client_id bigint,
    url character varying(255) NOT NULL,
    wsdllocation character varying(255),
    disabled boolean NOT NULL,
    disablednotice character varying(255),
    refresheddate timestamp without time zone,
    content text
);


ALTER TABLE public.wsdl OWNER TO serverconf;

--
-- Name: service_securitycategories id; Type: DEFAULT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.service_securitycategories ALTER COLUMN id SET DEFAULT nextval('public.service_securitycategories_id_seq'::regclass);


--
-- Data for Name: accessright; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.accessright (id, subjectid, rightsgiven, acl_id, servicecode, client_id, path, verbmask) FROM stdin;
\.


--
-- Data for Name: apikey; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.apikey (id, hash, username, status, description, addeddate) FROM stdin;
\.


--
-- Data for Name: certificate; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.certificate (id, key_id, alias, clientinstance, clientclass, clientcode, clientsubsystem, active, status, data) FROM stdin;
\.


--
-- Data for Name: certificaterequest; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.certificaterequest (id, key_id, alias, clientinstance, clientclass, clientcode, clientsubsystem, subjectname) FROM stdin;
\.


--
-- Data for Name: client; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.client (id, conf_id, identifier, clientstatus, isauthentication) FROM stdin;
\.


--
-- Data for Name: clientcertificate; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.clientcertificate (id, data, client_id) FROM stdin;
\.


--
-- Data for Name: databasechangelog; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.databasechangelog (id, author, filename, dateexecuted, orderexecuted, exectype, md5sum, description, comments, tag, liquibase, contexts, labels, deployment_id) FROM stdin;
0-initial	toja	serverconf/0-initial.xml	2025-05-10 15:48:58.437759	1	EXECUTED	9:0578a4ff4a09b53d45963d1fc145efb4	createTable tableName=ACL; createTable tableName=AUTHORIZEDSUBJECT; createTable tableName=CERTIFICATE; createTable tableName=CLIENT; createTable tableName=GROUPMEMBER; createTable tableName=IDENTIFIER; createTable tableName=LOCALGROUP; createTable...		\N	4.29.2	\N	\N	6892138132
1-indices	toja	serverconf/1-indices.xml	2025-05-10 15:48:58.48451	2	EXECUTED	9:96f6e8b236240a1f3a1ed4a9a4bc9244	createIndex indexName=SERVERCONF_OWNER_fkey, tableName=SERVERCONF; createIndex indexName=LOCALGROUP_CLIENT_ID_fkey, tableName=LOCALGROUP; createIndex indexName=ACL_CLIENT_ID_fkey, tableName=ACL; createIndex indexName=AUTHORIZEDSUBJECT_SUBJECTID_fk...		\N	4.29.2	\N	\N	6892138132
2-wsdlpublish	toja	serverconf/2-wsdlpublish.xml	2025-05-10 15:48:58.492289	3	EXECUTED	9:9aba06b6dc1d6bf0151a339d233d1f4b	dropColumn columnName=PUBLISH, tableName=WSDL; dropColumn columnName=PUBLISHEDDATE, tableName=WSDL		\N	4.29.2	\N	\N	6892138132
3-history	toja	serverconf/3-history.xml	2025-05-10 15:48:58.548995	4	EXECUTED	9:0c1d32ba7119493b7f922165417ba064	createTable tableName=history; addPrimaryKey tableName=history; sql		\N	4.29.2	\N	\N	6892138132
4.pre1-refactoring	toja	serverconf/4-refactoring.xml	2025-05-10 15:48:58.602856	5	MARK_RAN	9:d39c5b4b22ab5875d713efeeaa62a95a	dropUniqueConstraint constraintName=AUTHORIZEDSUBPK, tableName=AUTHORIZEDSUBJECT		\N	4.29.2	\N	\N	6892138132
4.pre2-refactoring	toja	serverconf/4-refactoring.xml	2025-05-10 15:48:58.829696	6	EXECUTED	9:6cf4f48e7854bbf862fcd1befb862b3f	dropUniqueConstraint constraintName=AUTHORIZEDSUBJECTPK, tableName=AUTHORIZEDSUBJECT		\N	4.29.2	\N	\N	6892138132
4-refactoring	toja	serverconf/4-refactoring.xml	2025-05-10 15:48:58.865504	7	EXECUTED	9:657b9a69d96711bcbe2874e52f5a7129	renameTable newTableName=ACCESSRIGHT, oldTableName=AUTHORIZEDSUBJECT; addColumn tableName=ACCESSRIGHT; addPrimaryKey constraintName=ACCESSRIGHTPK, tableName=ACCESSRIGHT; addForeignKeyConstraint baseTableName=ACCESSRIGHT, constraintName=FK_CS3RKN8I...		\N	4.29.2	\N	\N	6892138132
5-backendtype	toja	serverconf/5-backendtype.xml	2025-05-10 15:48:58.872024	8	EXECUTED	9:0faee5dfa082c4f0c78a238e8d194aff	dropColumn columnName=BACKEND, tableName=WSDL; dropColumn columnName=BACKENDURL, tableName=WSDL		\N	4.29.2	\N	\N	6892138132
6-wsdlcontent	toja	serverconf/6-wsdlcontent.xml	2025-05-10 15:48:58.877137	9	EXECUTED	9:2561eb343126c1e8b90cc0193fed273c	addColumn tableName=WSDL		\N	4.29.2	\N	\N	6892138132
7-serviceoneway	toja	serverconf/7-serviceoneway.xml	2025-05-10 15:48:58.881503	10	EXECUTED	9:3de8546eb83da313dd4f3623abe88b03	addColumn tableName=SERVICE		\N	4.29.2	\N	\N	6892138132
8-restapi	toja	serverconf/8-restapi.xml	2025-05-10 15:48:58.898624	11	EXECUTED	9:c07f4a552f95c6ec4dc76b12cbab78ee	createTable tableName=RESTAPI; addPrimaryKey constraintName=RESTAPIPK, tableName=RESTAPI; addForeignKeyConstraint baseTableName=RESTAPI, constraintName=FK_N8AJT5FKCRHHKSYDFFVE1BRO4, referencedTableName=CLIENT		\N	4.29.2	\N	\N	6892138132
9-ownerauthtype	ilja	serverconf/9-ownerauthtype.xml	2025-05-10 15:48:58.904096	12	EXECUTED	9:79eee46226248f117c9712c52c8a3bf8	update tableName=CLIENT		\N	4.29.2	\N	\N	6892138132
10-localgroupuq	indrek	serverconf/10-localgroupuq.xml	2025-05-10 15:48:58.910979	13	EXECUTED	9:b16054bdf92851e2cb59308cfc239518	addUniqueConstraint constraintName=LOCALGROUP_UQ, tableName=localgroup		\N	4.29.2	\N	\N	6892138132
11-restapiendpoint	iljak	serverconf/11-restapiendpoint.xml	2025-05-10 15:48:58.93749	14	EXECUTED	9:f42a3d8ce2da15d5e2d3202caa4eac91	createTable tableName=ENDPOINT; addColumn tableName=ACCESSRIGHT; addPrimaryKey constraintName=ENDPOINTPK, tableName=ENDPOINT; addForeignKeyConstraint baseTableName=ENDPOINT, constraintName=FK_OWDYAKXTF76H1TECBJ1YJD7F1, referencedTableName=RESTAPI;...		\N	4.29.2	\N	\N	6892138132
12-httpheaders	iljak	serverconf/12-httpheaders.xml	2025-05-10 15:48:58.971681	15	EXECUTED	9:84a96b754abd42b4c4f29d8f3edc07bf	createTable tableName=HTTPHEADER; addPrimaryKey constraintName=HTTPHEADERPK, tableName=HTTPHEADER; addForeignKeyConstraint baseTableName=HTTPHEADER, constraintName=FK_HTTPHEADER_RESTAPI, referencedTableName=RESTAPI; addForeignKeyConstraint baseTab...		\N	4.29.2	\N	\N	6892138132
13-serverconfimport	cyber	serverconf/13-serverconfimport.xml	2025-05-10 15:48:59.006974	16	EXECUTED	9:26f1d133918a4cb3d67541de4650c1de	createTable tableName=IMPORTINFO; addPrimaryKey constraintName=IMPORTINFOPK, tableName=IMPORTINFO; addForeignKeyConstraint baseTableName=IMPORTINFO, constraintName=FK_IMPORTINFO_IDENTIFIER, referencedTableName=IDENTIFIER; addForeignKeyConstraint b...		\N	4.29.2	\N	\N	6892138132
14-openapi	cyber	serverconf/14-openapi.xml	2025-05-10 15:48:59.028591	17	EXECUTED	9:1d256a75ef8bce3c67b0ef03642d25f3	createTable tableName=OPENAPI; addPrimaryKey constraintName=OPENAPIPK, tableName=OPENAPI; addForeignKeyConstraint baseTableName=OPENAPI, constraintName=FK_OPENAPI_RESTAPI, referencedTableName=RESTAPI; addUniqueConstraint constraintName=UC_OPENAPI_...		\N	4.29.2	\N	\N	6892138132
15-fix-empty-service-version	cyber	serverconf/15-fix-empty-service-version.xml	2025-05-10 15:48:59.033714	18	EXECUTED	9:3c511077e13ba663e0f3c30e13db3c9d	sql		\N	4.29.2	\N	\N	6892138132
16-unique-names-of-approved-tsas	cyber	serverconf/16-unique-names-of-approved-tsas.xml	2025-05-10 15:48:59.042346	19	EXECUTED	9:87092b6c2930785b7f49200de3f16216	sql; addUniqueConstraint constraintName=UC_TSP_NAME, tableName=TSP		\N	4.29.2	\N	\N	6892138132
17-api-key	cyber	serverconf/17-api-key.xml	2025-05-10 15:48:59.055073	20	EXECUTED	9:8b759a75af0e7d9893c4f0c16128755f	createTable tableName=APIKEY; addPrimaryKey constraintName=APIKEYPK, tableName=APIKEY		\N	4.29.2	\N	\N	6892138132
18-api-key-uniqueness	cyber	serverconf/18-api-key-uniqueness.xml	2025-05-10 15:48:59.061163	21	EXECUTED	9:49ff52968dd698183a16d82ddf50189d	addUniqueConstraint constraintName=UC_APIKEY_HASH, tableName=APIKEY		\N	4.29.2	\N	\N	6892138132
19-fix-openapi-baseurl-uc	cyber	serverconf/19-fix-openapi-baseurl-uc.xml	2025-05-10 15:48:59.069048	22	EXECUTED	9:c72718c585e72fbeac561bee4f2da6cc	dropUniqueConstraint constraintName=UC_OPENAPIBASEURL_OPENAPI, tableName=OPENAPIBASEURL; addUniqueConstraint constraintName=UC_OPENAPIBASEURL_OPENAPI, tableName=OPENAPIBASEURL		\N	4.29.2	\N	\N	6892138132
20-api-key-info	cyber	serverconf/20-api-key-info.xml	2025-05-10 15:48:59.077411	23	EXECUTED	9:c2f9e5eb7fb2b8186a07e1a15fd73a23	addColumn tableName=APIKEY		\N	4.29.2	\N	\N	6892138132
21-keyconf	cyber	serverconf/21-keyconf.xml	2025-05-10 15:48:59.158585	24	EXECUTED	9:a4e19daf80d5207f3bcc3b9517d86440	createTable tableName=TOKEN; addPrimaryKey constraintName=TOKENPK, tableName=TOKEN; addForeignKeyConstraint baseTableName=TOKEN, constraintName=FK_TOKEN_SERVERCONF, referencedTableName=SERVERCONF; addUniqueConstraint constraintName=TOKEN_UQ, table...		\N	4.29.2	\N	\N	6892138132
22-drop-history	cyber	serverconf/22-drop-history.xml	2025-05-10 15:48:59.173876	25	EXECUTED	9:c950a2b27359416f81a6766aef8b5e27	sql; dropTable tableName=history		\N	4.29.2	\N	\N	6892138132
23-device	cyber	serverconf/23-device.xml	2025-05-10 15:48:59.201392	26	EXECUTED	9:4663ad21ac9014738bf4d5563be4656f	createTable tableName=DEVICE; addPrimaryKey constraintName=DEVICEPK, tableName=DEVICE; addForeignKeyConstraint baseTableName=DEVICE, constraintName=FK_DEVICE_SERVERCONF, referencedTableName=SERVERCONF; addColumn tableName=TOKEN; addForeignKeyConst...		\N	4.29.2	\N	\N	6892138132
24-variable	cyber	serverconf/24-variable.xml	2025-05-10 15:48:59.214363	27	EXECUTED	9:eca29f3e46210f2bd19e133ddb52e0c6	createTable tableName=VARIABLE; addPrimaryKey constraintName=VARIABLEPK, tableName=VARIABLE; addUniqueConstraint constraintName=UC_VARIABLE_KEY, tableName=VARIABLE		\N	4.29.2	\N	\N	6892138132
25-token-member-id	cyber	serverconf/25-token-member-id.xml	2025-05-10 15:48:59.222251	28	EXECUTED	9:10af601e79a223c6c2d2a9ca056b6a90	addColumn tableName=TOKEN		\N	4.29.2	\N	\N	6892138132
26-csr-subjectname-length	cyber	serverconf/26-csr-subjectname-length.xml	2025-05-10 15:48:59.226798	29	EXECUTED	9:423e651816b543eaff98261d8987d6a7	modifyDataType columnName=SUBJECTNAME, tableName=CERTIFICATEREQUEST		\N	4.29.2	\N	\N	6892138132
27-device-batch-signing-attribute	cyber	serverconf/27-device-batch-signing-attribute.xml	2025-05-10 15:48:59.231306	30	EXECUTED	9:068a5d5d12e5ed6157080c143aea85d4	renameColumn newColumnName=BATCHSIGNINGENABLED, oldColumnName=BATCHSIGNINGSUPPORTED, tableName=DEVICE		\N	4.29.2	\N	\N	6892138132
28-http-header-value-length	cyber	serverconf/28-http-header-value-length.xml	2025-05-10 15:48:59.23553	31	EXECUTED	9:c5fa07ec718c90cfbab99114d845ab7d	modifyDataType columnName=VALUE, tableName=HTTPHEADER		\N	4.29.2	\N	\N	6892138132
\.


--
-- Data for Name: databasechangeloglock; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.databasechangeloglock (id, locked, lockgranted, lockedby) FROM stdin;
1	f	\N	\N
\.


--
-- Data for Name: device; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.device (id, conf_id, name, description, type, disabled, batchsigningenabled, configuration, updateddate) FROM stdin;
\.


--
-- Data for Name: endpoint; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.endpoint (id, restapi_id, path, generated, addeddate) FROM stdin;
\.


--
-- Data for Name: groupmember; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.groupmember (id, groupmemberid, added, localgroup_id) FROM stdin;
\.


--
-- Data for Name: httpheader; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.httpheader (id, restapi_id, service_id, key, value, action) FROM stdin;
\.


--
-- Data for Name: identifier; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.identifier (id, discriminator, type, xroadinstance, memberclass, membercode, subsystemcode, serviceversion, servicecode, groupcode, securitycategory, servercode) FROM stdin;
\.


--
-- Data for Name: importclientdiff; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.importclientdiff (id, clientid, missing, importinfo_id) FROM stdin;
\.


--
-- Data for Name: importinfo; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.importinfo (id, version, exporteddate, securityserverid, ip, hostname, missingclientaction, redundantclientaction, aborted, importeddate, conf_id) FROM stdin;
\.


--
-- Data for Name: key; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.key (id, token_id, alias, algorithm, publickey, name, type) FROM stdin;
\.


--
-- Data for Name: localgroup; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.localgroup (id, groupcode, description, updated, client_id) FROM stdin;
\.


--
-- Data for Name: openapi; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.openapi (id, restapi_id, descriptionurl, refresheddate, content) FROM stdin;
\.


--
-- Data for Name: openapibaseurl; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.openapibaseurl (id, openapi_id, url) FROM stdin;
\.


--
-- Data for Name: restapi; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.restapi (id, client_id, disabled, disablednotice, servicecode, serviceversion, baseurl, sslauthentication, timeout, addeddate) FROM stdin;
\.


--
-- Data for Name: serverconf; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.serverconf (id, servercode, owner) FROM stdin;
34	\N	\N
\.


--
-- Data for Name: service; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.service (id, wsdl_id, servicecode, serviceversion, title, url, sslauthentication, timeout, oneway) FROM stdin;
\.


--
-- Data for Name: service_securitycategories; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.service_securitycategories (service_id, security_cat_id, id) FROM stdin;
\.


--
-- Data for Name: token; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.token (id, conf_id, alias, type, name, device_id, memberinstance, memberclass, membercode) FROM stdin;
1	\N	0	softToken	softToken-0	\N	\N	\N	\N
\.


--
-- Data for Name: tsp; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.tsp (id, name, url, conf_id) FROM stdin;
\.


--
-- Data for Name: uiuser; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.uiuser (id, username, locale) FROM stdin;
\.


--
-- Data for Name: variable; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.variable (id, name, value) FROM stdin;
\.


--
-- Data for Name: wsdl; Type: TABLE DATA; Schema: public; Owner: serverconf
--

COPY public.wsdl (id, client_id, url, wsdllocation, disabled, disablednotice, refresheddate, content) FROM stdin;
\.


--
-- Name: apikey_id_seq; Type: SEQUENCE SET; Schema: public; Owner: serverconf
--

SELECT pg_catalog.setval('public.apikey_id_seq', 1, false);


--
-- Name: hibernate_sequence; Type: SEQUENCE SET; Schema: public; Owner: serverconf
--

SELECT pg_catalog.setval('public.hibernate_sequence', 66, true);


--
-- Name: service_securitycategories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: serverconf
--

SELECT pg_catalog.setval('public.service_securitycategories_id_seq', 1, false);


--
-- Name: accessright accessrightpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.accessright
    ADD CONSTRAINT accessrightpk PRIMARY KEY (id);


--
-- Name: apikey apikeypk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.apikey
    ADD CONSTRAINT apikeypk PRIMARY KEY (id);


--
-- Name: certificate certificate_uq; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT certificate_uq UNIQUE (alias, key_id);


--
-- Name: certificate certificatepk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT certificatepk PRIMARY KEY (id);


--
-- Name: certificaterequest certificaterequest_uq; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.certificaterequest
    ADD CONSTRAINT certificaterequest_uq UNIQUE (alias, key_id);


--
-- Name: certificaterequest certificaterequestpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.certificaterequest
    ADD CONSTRAINT certificaterequestpk PRIMARY KEY (id);


--
-- Name: clientcertificate clientcertificatepk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.clientcertificate
    ADD CONSTRAINT clientcertificatepk PRIMARY KEY (id);


--
-- Name: client clientpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT clientpk PRIMARY KEY (id);


--
-- Name: databasechangeloglock databasechangeloglock_pkey; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.databasechangeloglock
    ADD CONSTRAINT databasechangeloglock_pkey PRIMARY KEY (id);


--
-- Name: device devicepk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT devicepk PRIMARY KEY (id);


--
-- Name: endpoint endpointpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.endpoint
    ADD CONSTRAINT endpointpk PRIMARY KEY (id);


--
-- Name: groupmember groupmemberpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.groupmember
    ADD CONSTRAINT groupmemberpk PRIMARY KEY (id);


--
-- Name: httpheader httpheaderpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.httpheader
    ADD CONSTRAINT httpheaderpk PRIMARY KEY (id);


--
-- Name: identifier identifierpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.identifier
    ADD CONSTRAINT identifierpk PRIMARY KEY (id);


--
-- Name: importclientdiff importclientdiffpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.importclientdiff
    ADD CONSTRAINT importclientdiffpk PRIMARY KEY (id);


--
-- Name: importinfo importinfopk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.importinfo
    ADD CONSTRAINT importinfopk PRIMARY KEY (id);


--
-- Name: key key_uq; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.key
    ADD CONSTRAINT key_uq UNIQUE (alias, token_id);


--
-- Name: key keypk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.key
    ADD CONSTRAINT keypk PRIMARY KEY (id);


--
-- Name: localgroup localgroup_uq; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.localgroup
    ADD CONSTRAINT localgroup_uq UNIQUE (groupcode, client_id);


--
-- Name: localgroup localgrouppk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.localgroup
    ADD CONSTRAINT localgrouppk PRIMARY KEY (id);


--
-- Name: openapibaseurl openapibaseurlpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.openapibaseurl
    ADD CONSTRAINT openapibaseurlpk PRIMARY KEY (id);


--
-- Name: openapi openapipk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.openapi
    ADD CONSTRAINT openapipk PRIMARY KEY (id);


--
-- Name: restapi restapipk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.restapi
    ADD CONSTRAINT restapipk PRIMARY KEY (id);


--
-- Name: serverconf serverconfpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.serverconf
    ADD CONSTRAINT serverconfpk PRIMARY KEY (id);


--
-- Name: service_securitycategories service_securitycategories_id_key; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.service_securitycategories
    ADD CONSTRAINT service_securitycategories_id_key UNIQUE (id);


--
-- Name: service servicepk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT servicepk PRIMARY KEY (id);


--
-- Name: token token_uq; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT token_uq UNIQUE (alias);


--
-- Name: token tokenpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT tokenpk PRIMARY KEY (id);


--
-- Name: tsp tsppk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.tsp
    ADD CONSTRAINT tsppk PRIMARY KEY (id);


--
-- Name: endpoint uc_3x6g6h4ismx2ry2tg3nyp45h6; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.endpoint
    ADD CONSTRAINT uc_3x6g6h4ismx2ry2tg3nyp45h6 UNIQUE (restapi_id, path);


--
-- Name: apikey uc_apikey_hash; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.apikey
    ADD CONSTRAINT uc_apikey_hash UNIQUE (hash);


--
-- Name: httpheader uc_httpheader_restapi; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.httpheader
    ADD CONSTRAINT uc_httpheader_restapi UNIQUE (restapi_id, key);


--
-- Name: httpheader uc_httpheader_service; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.httpheader
    ADD CONSTRAINT uc_httpheader_service UNIQUE (service_id, key);


--
-- Name: openapi uc_openapi_restapi; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.openapi
    ADD CONSTRAINT uc_openapi_restapi UNIQUE (restapi_id, descriptionurl);


--
-- Name: openapibaseurl uc_openapibaseurl_openapi; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.openapibaseurl
    ADD CONSTRAINT uc_openapibaseurl_openapi UNIQUE (url, openapi_id);


--
-- Name: tsp uc_tsp_name; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.tsp
    ADD CONSTRAINT uc_tsp_name UNIQUE (name);


--
-- Name: variable uc_variable_key; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.variable
    ADD CONSTRAINT uc_variable_key UNIQUE (name);


--
-- Name: uiuser uiuserpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.uiuser
    ADD CONSTRAINT uiuserpk PRIMARY KEY (id);


--
-- Name: variable variablepk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.variable
    ADD CONSTRAINT variablepk PRIMARY KEY (id);


--
-- Name: wsdl wsdlpk; Type: CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.wsdl
    ADD CONSTRAINT wsdlpk PRIMARY KEY (id);


--
-- Name: AUTHORIZEDSUBJECT_ACL_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "AUTHORIZEDSUBJECT_ACL_ID_fkey" ON public.accessright USING btree (acl_id);


--
-- Name: AUTHORIZEDSUBJECT_SUBJECTID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "AUTHORIZEDSUBJECT_SUBJECTID_fkey" ON public.accessright USING btree (subjectid);


--
-- Name: CLIENT_CONF_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "CLIENT_CONF_ID_fkey" ON public.client USING btree (conf_id);


--
-- Name: CLIENT_IDENTIFIER_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "CLIENT_IDENTIFIER_fkey" ON public.client USING btree (identifier);


--
-- Name: GROUPMEMBER_GROUPMEMBERID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "GROUPMEMBER_GROUPMEMBERID_fkey" ON public.groupmember USING btree (groupmemberid);


--
-- Name: GROUPMEMBER_LOCALGROUP_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "GROUPMEMBER_LOCALGROUP_ID_fkey" ON public.groupmember USING btree (localgroup_id);


--
-- Name: LOCALGROUP_CLIENT_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "LOCALGROUP_CLIENT_ID_fkey" ON public.localgroup USING btree (client_id);


--
-- Name: SERVERCONF_OWNER_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "SERVERCONF_OWNER_fkey" ON public.serverconf USING btree (owner);


--
-- Name: SERVICE_SECURITYCATEGORIES_SECURITY_CAT_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "SERVICE_SECURITYCATEGORIES_SECURITY_CAT_ID_fkey" ON public.service_securitycategories USING btree (security_cat_id);


--
-- Name: SERVICE_SECURITYCATEGORIES_SERVICE_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "SERVICE_SECURITYCATEGORIES_SERVICE_ID_fkey" ON public.service_securitycategories USING btree (service_id);


--
-- Name: SERVICE_WSDL_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "SERVICE_WSDL_ID_fkey" ON public.service USING btree (wsdl_id);


--
-- Name: TSP_CONF_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "TSP_CONF_ID_fkey" ON public.tsp USING btree (conf_id);


--
-- Name: WSDL_CLIENT_ID_fkey; Type: INDEX; Schema: public; Owner: serverconf
--

CREATE INDEX "WSDL_CLIENT_ID_fkey" ON public.wsdl USING btree (client_id);


--
-- Name: serverconf fk_1feb23ww1ondj5dv8eu6gp86o; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.serverconf
    ADD CONSTRAINT fk_1feb23ww1ondj5dv8eu6gp86o FOREIGN KEY (owner) REFERENCES public.client(id);


--
-- Name: localgroup fk_3hbuo4vaqc9xpgq8ombxsfuqa; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.localgroup
    ADD CONSTRAINT fk_3hbuo4vaqc9xpgq8ombxsfuqa FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: accessright fk_5vnw7dq6i9x7eob71bp7jym42; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.accessright
    ADD CONSTRAINT fk_5vnw7dq6i9x7eob71bp7jym42 FOREIGN KEY (subjectid) REFERENCES public.identifier(id);


--
-- Name: groupmember fk_7htiw4bes7513yvehdp9o1ccn; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.groupmember
    ADD CONSTRAINT fk_7htiw4bes7513yvehdp9o1ccn FOREIGN KEY (groupmemberid) REFERENCES public.identifier(id);


--
-- Name: groupmember fk_9s9v7iqgb50l3n9xnxfia82p1; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.groupmember
    ADD CONSTRAINT fk_9s9v7iqgb50l3n9xnxfia82p1 FOREIGN KEY (localgroup_id) REFERENCES public.localgroup(id);


--
-- Name: certificate fk_certificate_key; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.certificate
    ADD CONSTRAINT fk_certificate_key FOREIGN KEY (key_id) REFERENCES public.key(id);


--
-- Name: certificaterequest fk_certificaterequest_key; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.certificaterequest
    ADD CONSTRAINT fk_certificaterequest_key FOREIGN KEY (key_id) REFERENCES public.key(id);


--
-- Name: accessright fk_cs3rkn8ilbyf6hnoeto8xhu68; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.accessright
    ADD CONSTRAINT fk_cs3rkn8ilbyf6hnoeto8xhu68 FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: device fk_device_serverconf; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.device
    ADD CONSTRAINT fk_device_serverconf FOREIGN KEY (conf_id) REFERENCES public.serverconf(id);


--
-- Name: httpheader fk_httpheader_restapi; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.httpheader
    ADD CONSTRAINT fk_httpheader_restapi FOREIGN KEY (restapi_id) REFERENCES public.restapi(id);


--
-- Name: httpheader fk_httpheader_service; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.httpheader
    ADD CONSTRAINT fk_httpheader_service FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: wsdl fk_i1xxlscwb84540u33au7ff9vb; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.wsdl
    ADD CONSTRAINT fk_i1xxlscwb84540u33au7ff9vb FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: importclientdiff fk_importclientdiff_identifier; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.importclientdiff
    ADD CONSTRAINT fk_importclientdiff_identifier FOREIGN KEY (clientid) REFERENCES public.identifier(id);


--
-- Name: importclientdiff fk_importclientdiff_importinfo; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.importclientdiff
    ADD CONSTRAINT fk_importclientdiff_importinfo FOREIGN KEY (importinfo_id) REFERENCES public.importinfo(id);


--
-- Name: importinfo fk_importinfo_identifier; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.importinfo
    ADD CONSTRAINT fk_importinfo_identifier FOREIGN KEY (securityserverid) REFERENCES public.identifier(id);


--
-- Name: importinfo fk_importinfo_serverconf; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.importinfo
    ADD CONSTRAINT fk_importinfo_serverconf FOREIGN KEY (conf_id) REFERENCES public.serverconf(id);


--
-- Name: service_securitycategories fk_jug7e4jtiiojg492hh1i10qr0; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.service_securitycategories
    ADD CONSTRAINT fk_jug7e4jtiiojg492hh1i10qr0 FOREIGN KEY (security_cat_id) REFERENCES public.identifier(id);


--
-- Name: key fk_key_token; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.key
    ADD CONSTRAINT fk_key_token FOREIGN KEY (token_id) REFERENCES public.token(id);


--
-- Name: restapi fk_n8ajt5fkcrhhksydffve1bro4; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.restapi
    ADD CONSTRAINT fk_n8ajt5fkcrhhksydffve1bro4 FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: openapi fk_openapi_restapi; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.openapi
    ADD CONSTRAINT fk_openapi_restapi FOREIGN KEY (restapi_id) REFERENCES public.restapi(id);


--
-- Name: openapibaseurl fk_openapibaseurl_openapi; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.openapibaseurl
    ADD CONSTRAINT fk_openapibaseurl_openapi FOREIGN KEY (openapi_id) REFERENCES public.openapi(id);


--
-- Name: service_securitycategories fk_or1xkhdc830058rh2kpdgjvd0; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.service_securitycategories
    ADD CONSTRAINT fk_or1xkhdc830058rh2kpdgjvd0 FOREIGN KEY (service_id) REFERENCES public.service(id);


--
-- Name: endpoint fk_owdyakxtf76h1tecbj1yjd7f1; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.endpoint
    ADD CONSTRAINT fk_owdyakxtf76h1tecbj1yjd7f1 FOREIGN KEY (restapi_id) REFERENCES public.restapi(id);


--
-- Name: client fk_p1n5e2yp385eusd471lon18lm; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fk_p1n5e2yp385eusd471lon18lm FOREIGN KEY (conf_id) REFERENCES public.serverconf(id);


--
-- Name: service fk_q2me40qtkcypwyh6ttrrpf5xf; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.service
    ADD CONSTRAINT fk_q2me40qtkcypwyh6ttrrpf5xf FOREIGN KEY (wsdl_id) REFERENCES public.wsdl(id);


--
-- Name: tsp fk_sae6cb6emxn9iy5h56bq8ier2; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.tsp
    ADD CONSTRAINT fk_sae6cb6emxn9iy5h56bq8ier2 FOREIGN KEY (conf_id) REFERENCES public.serverconf(id);


--
-- Name: clientcertificate fk_sm6kk4lbadiiis4mj1ltp15h9; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.clientcertificate
    ADD CONSTRAINT fk_sm6kk4lbadiiis4mj1ltp15h9 FOREIGN KEY (client_id) REFERENCES public.client(id);


--
-- Name: client fk_th1b8viw7rfxp53t1b27oscv1; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.client
    ADD CONSTRAINT fk_th1b8viw7rfxp53t1b27oscv1 FOREIGN KEY (identifier) REFERENCES public.identifier(id);


--
-- Name: token fk_token_device; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fk_token_device FOREIGN KEY (device_id) REFERENCES public.device(id);


--
-- Name: token fk_token_serverconf; Type: FK CONSTRAINT; Schema: public; Owner: serverconf
--

ALTER TABLE ONLY public.token
    ADD CONSTRAINT fk_token_serverconf FOREIGN KEY (conf_id) REFERENCES public.serverconf(id);


--
-- PostgreSQL database dump complete
--

