apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-rwx
parameters:
  accessMode: ReadWriteMany
  nfsOptions: vers=4.1
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate