{{- with .Values.trembita_config.secrets.proxy_tls_healthcheck}}
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
  name: {{ .name }}-init-sa
{{- end}}