apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trembita-1-22-6-ss.fullname" . }}-init-ca-job
spec:
  template:
    spec:
      serviceAccountName: {{ include "trembita-1-22-6-ss.fullname" . }}-init-sa
      restartPolicy: OnFailure
      containers:
        - name: generate-cert
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
                openssl req -x509 -nodes -newkey rsa:2048 -days 365 \
                  -subj "/CN={{ include "trembita-1-22-6-ss.fullname" . }}" \
                  -keyout /tmp/tls.key -out /tmp/tls.crt

                kubectl create secret tls {{ include "trembita-1-22-6-ss.fullname" . }}-cert \
                  --cert=/tmp/tls.crt --key=/tmp/tls.key \
                  --namespace={{ .Release.Namespace }} --dry-run=client -o yaml | kubectl apply -f -