apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "trembita-1-22-6-ss.fullname" . }}-secret-writer
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update"]