{{- with .Values.trembita_config.trembita_identity_provider_rest_api_pod}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: {{ .name}}
          image: {{.image}}
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 8087 {{/*port for authentication REST api*/}}
          resources:
            requests:
              cpu: "400m"       # garantee 0.4 ядра
              memory: "256Mi"   # garantee 256 МБ
            limits:
              cpu: "600m"       # max 0.6 ядра
              memory: "512Mi"     # max 512 МБ
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end }}