{{- with .Values.trembita_config.trembita_identity_provider_rest_api_pod}}
{{- $ctx := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: {{ .name}}
          image: {{.image}}
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 8087 {{/*port for authentication REST api*/}}
          resources:
            requests:
              cpu: "400m"       # garantee 0.4 ядра
              memory: "256Mi"   # garantee 256 МБ
            limits:
              cpu: "600m"       # max 0.6 ядра
              memory: "512Mi"     # max 512 МБ
          command: [ "/opt/java/openjdk/bin/java" ]
          args:
            - "-Xmx128m"
            - "-Xshare:on"
            - "-XX:MaxMetaspaceSize=256m"
            - "-XX:+UseG1GC"
            - "-cp"
            - "/app/jlib/identity-provider-rest-api.jar"
            - "-Dfile.encoding=UTF-8"
            - "-Djava.library.path=/usr/share/uxp/lib/"
            - "-Dorg.bytedeco.javacpp.cachedir=/tmp/bc_java"
            - "-Dserver.port=8087"
            - "-Dlogging.config=/app/identity-provider-rest-api-logback.xml"
            - "-Duxp.identity-provider.security-server-client-id=60997vl7jlgoi53zbyvv2k9iyny1rae2"
            - "-Duxp.identity-provider.security-server-client-secret=QTK3fBuPu0v0m2DpvEees0AODujEcX3V"
            - "-Duxp.identity-provider.database-properties=/etc/uxp/db.properties"
{{/*            - "-Duxp.identity-provider.oauth2-issuer-location="*/}}
            - "-Duxp.identity-provider.bcrypt.log-rounds=10"
            - "-Duxp.identity-provider.login-max-failed-attempts=5"
            - "-Duxp.identity-provider.public-client-redirect-uris=https://trembita.office"
            - "-Duxp.identity-provider.hostname=trembita.office"
            - "-Duxp.identity-provider.public-client-id=uxp-ss-ui"
            - "-Duxp.identity-provider.oauth2-introspect-uri=http://localhost:8087/auth-api/v1/oauth2/introspect"
            - "-Duxp.identity-provider.login-lockout-time-duration=15"
            - "-Duxp.identity-provider.public-client-access-token-time-to-live=180"
            - "org.springframework.boot.loader.PropertiesLauncher"
          securityContext:
            readOnlyRootFilesystem: true
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end }}