apiVersion: v1
kind: Service
metadata:
  name: identity-provider-rest-api-service
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
  selector:
    app: identity-provider-rest-api