apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "trembita-1-22-6-ss.fullname" . }}-db-init
  labels:
    app.kubernetes.io/name: {{ include "trembita-1-22-6-ss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: db-init
spec:
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: db-init
          image: "{{ .Values.postgresql.initJob.containerImageName }}:{{ .Values.postgresql.initJob.containerImageVer }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: PGHOST
              value: {{ include "trembita-1-22-6-ss.fullname" . }}-postgres
            - name: PGPORT
              value: "5432"
            {{- range .Values.postgresql.initJob.env }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}