{{- if .Values.configMap -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  db.properties: |
    serverconf.hibernate.jdbc.use_streams_for_binary = true
    serverconf.hibernate.connection.driver_class = org.postgresql.Driver
    serverconf.hibernate.connection.url = jdbc:postgresql://{{ include "trembita-1-22-6-ss.fullname" . }}-postgres:5432/serverconf
    serverconf.hibernate.connection.username ={{ .Values.trembita_config.ss_to_db_access.SERVERCONF_DB_USER }}
    serverconf.hibernate.connection.password = {{ .Values.trembita_config.ss_to_db_access.SERVERCONF_DB_PASS }}
    messagelog-metadata.hibernate.connection.driver_class = org.postgresql.Driver
    messagelog-metadata.hibernate.connection.url = jdbc:postgresql://{{ include "trembita-1-22-6-ss.fullname" . }}-postgres:5432/messagelog-metadata
    messagelog-metadata.hibernate.connection.username ={{ .Values.trembita_config.ss_to_db_access.MESSAGELOG_DB_USER }}
    messagelog-metadata.hibernate.connection.password = {{ .Values.trembita_config.ss_to_db_access.MESSAGELOG_DB_PASS }}
    identity-provider.hibernate.connection.driver_class = org.postgresql.Driver
    identity-provider.hibernate.connection.url = jdbc:postgresql://{{ include "trembita-1-22-6-ss.fullname" . }}-postgres:5432/identity-provider
    identity-provider.hibernate.connection.username ={{ .Values.trembita_config.ss_to_db_access.IDENTITY_DB_USER }}
    identity-provider.hibernate.connection.password ={{ .Values.trembita_config.ss_to_db_access.IDENTITY_DB_PASS }}
    op-monitor.hibernate.jdbc.use_streams_for_binary = true
    op-monitor.hibernate.connection.driver_class = org.postgresql.Driver
    op-monitor.hibernate.jdbc.batch_size = 50
    op-monitor.hibernate.connection.url = jdbc:postgresql://{{ include "trembita-1-22-6-ss.fullname" . }}-postgres:5432/op-monitor
    op-monitor.hibernate.connection.username = {{ .Values.trembita_config.ss_to_db_access.OPMONITOR_DB_USER }}
    op-monitor.hibernate.connection.password = {{ .Values.trembita_config.ss_to_db_access.OPMONITOR_DB_PASS }}
{{- end }}