{{- with .Values.trembita_config.trembita_worker_pods}}
{{- if and .enabled .autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "trembita-1-22-6-ss.fullname" . }}-worker-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "trembita-1-22-6-ss.fullname" . }}-worker
  minReplicas: {{ .autoscaling.min }}
  maxReplicas: {{ .autoscaling.max }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.cpuUtilization }}
{{- end }}
{{- end }}