{{- if .Values.trembita_config.trembita_worker_pods.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trembita-1-22-6-ss.fullname" . }}-worker
  labels:
    app.kubernetes.io/name: {{ include "trembita-1-22-6-ss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: trembita-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "trembita-1-22-6-ss.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: worker
        app.kubernetes.image/: {{ .Values.trembita_config.trembita_worker_pods.image}}
        {{- if .Values.trembita_config.trembita_workers_tags.enabled }}
        {{- range $k, $v := .Values.trembita_config.trembita_workers_tags.tags }}
        {{ $k }}: {{ $v | quote }}
        {{- end }}
        {{- end }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.trembita_config.trembita_worker_pods.image}}"
          imagePullPolicy: IfNotPresent
{{/*          resources:*/}}
{{/*            {{- toYaml .Values.worker.resources | nindent 12 }}*/}}
{{/*          env:*/}}
{{/*            {{- toYaml .Values.worker.env | nindent 12 }}*/}}
{{/*          volumeMounts:*/}}
{{/*            {{- toYaml .Values.worker.volumeMounts | nindent 12 }}*/}}
{{/*      volumes:*/}}
{{/*        {{- toYaml .Values.worker.volumes | nindent 8 }}*/}}
{{- end }}