{{- if and .Values.trembita_config.web_ui_access.configMaps.enabled .Values.trembita_config.web_ui_access.configMaps.local_ini.enabled}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.trembita_config.web_ui_access.configMaps.local_ini.name}}
data:
  {{ default "local.ini" .Values.trembita_config.web_ui_access.configMaps.local_ini.subPath}}: |
    [identity-provider]
    security-server-client-id = 60997vl7jlgoi53zbyvv2k9iyny1rae2
    security-server-client-secret = QTK3fBuPu0v0m2DpvEees0AODujEcX3V
    public-client-redirect-uris= https://trembita2.local
    hostname=trembita2.local


    [message-log]
    archive-storage-type = fs
{{- end}}

------

{{- if and .Values.trembita_config.web_ui_access.configMaps.enabled .Values.trembita_config.web_ui_access.configMaps.default_uxp.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.trembita_config.web_ui_access.configMaps.default_uxp.name }}
data:
  {{ default "uxp-default" .Values.trembita_config.web_ui_access.configMaps.default_uxp.subPath}}: |
    server {
      listen 4000;

      location /test {
          return 200 "OK - nginx is working\n";
          add_header Content-Type text/plain;
      }

      # Deny all hidden file requests
      location ~ /\. {
        deny all;
        return 404;
      }

      # Include general headers. This is explicitly defined here, because directives are not inherited
      # from the previous levels if "add_header" is defined in the current level. And uxp-*-headers
      # contains "add_header".
      include conf.d/uxp-headers.include;

      # Include component specific headers
      include conf.d/uxp-*-headers.include;

      # Include UXP locations
      include conf.d/uxp-*-location.include;
    }

{{- end }}

------

{{- if and .Values.trembita_config.web_ui_access.configMaps.enabled .Values.trembita_config.web_ui_access.configMaps.uxp_identity_provider_rest_api.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.trembita_config.web_ui_access.configMaps.uxp_identity_provider_rest_api.name }}
data:
  {{default "uxp-identity-provider-rest-api-location.include" .Values.trembita_config.web_ui_access.configMaps.uxp_identity_provider_rest_api.subPath}}: |
    # Identity Provider backend location.
    location /auth-api {
      proxy_pass http://127.0.0.1:8087;
    #  proxy_set_header Host $host:$server_port;
    #  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #  proxy_set_header X-Forwarded-Proto https;
    #  proxy_set_header X-Forwarded-Port $server_port;
    #  proxy_redirect http:// https://;
      client_max_body_size 5M;

      location ~* oauth2-redirect.html$ {
        proxy_pass http://127.0.0.1:8087;
    #    proxy_set_header Host $host:$server_port;
    #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header X-Forwarded-Proto https;
    #    proxy_set_header X-Forwarded-Port $server_port;
    #    proxy_redirect http:// https://;
    #    client_max_body_size 5M;
        add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-ancestors 'self'; script-src 'self' 'unsafe-inline';" always;
      }
    }

{{- end }}

------

{{- if and .Values.trembita_config.web_ui_access.configMaps.enabled .Values.trembita_config.web_ui_access.configMaps.uxp_securityserver_rest_api.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.trembita_config.web_ui_access.configMaps.uxp_securityserver_rest_api.name}}
data:
  {{default "uxp-securityserver-rest-api-location.include" .Values.trembita_config.web_ui_access.configMaps.uxp_securityserver_rest_api.subPath}}: |
    # REST API location.
      location /api {
        proxy_pass http://127.0.0.1:8085;
        #proxy_set_header Host $host:$server_port;
        #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #proxy_set_header X-Forwarded-Proto https;
        #proxy_set_header X-Forwarded-Port $server_port;
        #proxy_redirect http:// https://;
        #client_max_body_size 5M;

        location ~* oauth2-redirect.html$ {
          proxy_pass http://127.0.0.1:8085;
          #proxy_set_header Host $host:$server_port;
          #proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          #proxy_set_header X-Forwarded-Proto https;
          #proxy_set_header X-Forwarded-Port $server_port;
          #proxy_redirect http:// https://;
          #client_max_body_size 5M;
          add_header Content-Security-Policy "default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-ancestors 'self'; script-src 'self' 'unsafe-inline';" always;
        }
      }
{{- end}}

