{{- with .Values.trembita_config.trembita_worker_pods.secrets }}
{{- range $secretName, $secretCfg := . }}
{{- if $secretCfg.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" $.Release.Name $secretName }}
type: Opaque
stringData:
  {{ $filename := $secretCfg.filename | default (printf "%s.json" $secretName) }}
  {{ $filename }}: |
    {
    {{- $total := len $secretCfg.values }}
    {{- $count := 0 }}
    {{- range $k, $v := $secretCfg.values }}
      "{{ $k }}": "{{ $v }}"{{ if lt (add1 $count) $total }},{{ end }}
      {{- $count = add $count 1 }}
    {{- end }}
    }
---
{{- end }}
{{- end }}
{{- end }}