{{/*{{- if .Values.trembita_config.web_ui_access.service.enabled }}*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "trembita-1-22-6-ss.fullname" . }}-web*/}}
{{/*  labels:*/}}
{{/*    app: {{ include "trembita-1-22-6-ss.name" . }}*/}}
{{/*spec:*/}}
{{/*  type: {{ .Values.trembita_config.web_ui_access.service.type | default "ClusterIP" }}*/}}
{{/*  ports:*/}}
{{/*    - name: {{ .Values.trembita_config.web_ui_access.service.portName | default "http" }}*/}}
{{/*      port: {{ .Values.trembita_config.web_ui_access.service.port }}*/}}
{{/*      targetPort: {{ .Values.trembita_config.web_ui_access.service.port }}*/}}
{{/*  selector:*/}}
{{/*    app: {{ include "trembita-1-22-6-ss.name" . }}-{{ .Values.trembita_config.web_ui_access.service.label }}*/}}
{{/*{{- end }}*/}}

{{/*{{- range $key, $section := .Values.trembita_config }}*/}}
{{/*  {{- if and $section.service $section.service.enabled }}*/}}
{{/*  {{- $safeKey := replace "_" "-" $key }}*/}}
{{/*---*/}}
{{/*apiVersion: v1*/}}
{{/*kind: Service*/}}
{{/*metadata:*/}}
{{/*  name: {{ printf "trembita-%s-svc" $safeKey }}*/}}
{{/*  labels:*/}}
{{/*    app: {{ $safeKey }}*/}}
{{/*    role: {{ $section.service.label | default $safeKey }}*/}}
{{/*spec:*/}}
{{/*  type: {{ $section.service.type | default "ClusterIP" }}*/}}
{{/*  selector:*/}}
{{/*    {{- if hasKey $section.service "selectors" }}*/}}
{{/*    {{- range $tagKey, $tagVal := $section.service.selectors }}*/}}
{{/*    {{ $tagKey }}: {{ $tagVal | quote }}*/}}
{{/*    {{- end }}*/}}
{{/*    {{- end }}*/}}
{{/*  ports:*/}}
{{/*    - port: {{ $section.service.port }}*/}}
{{/*      targetPort: {{ $section.service.port }}*/}}
{{/*      protocol: TCP*/}}
{{/*      name: {{ $section.service.portName | default $safeKey }}*/}}
{{/*  {{- end }}*/}}
{{/*{{- end }}*/}}

{{/*---*/}}

{{/*{{- range $key, $section := .Values.trembita_config }}*/}}
{{/*  {{- if and $section.ingress $section.ingress.enabled }}*/}}
{{/*  {{- $safeKey := replace "_" "-" $key }}*/}}
{{/*---*/}}
{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{ printf "trembita-%s-ingress" $safeKey }}*/}}
{{/*  labels:*/}}
{{/*    app: {{ $safeKey }}*/}}
{{/*  annotations:*/}}
{{/*    {{- if $section.ingress.className }}*/}}
{{/*    kubernetes.io/ingress.class: {{ $section.ingress.className }}*/}}
{{/*    {{- end }}*/}}
{{/*spec:*/}}
{{/*  {{- if $section.ingress.tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range $tls := $section.ingress.tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range $host := $tls.hosts }}*/}}
{{/*        - {{ $host }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ $tls.secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}

{{/*  rules:*/}}
{{/*    {{- range $host := $section.ingress.hosts }}*/}}
{{/*    - host: {{ $host.host }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          {{- range $path := $host.paths }}*/}}
{{/*          - path: {{ $path.path }}*/}}
{{/*            pathType: {{ $path.pathType }}*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ printf "trembita-%s-svc" $safeKey }}*/}}
{{/*                port:*/}}
{{/*                  number: {{ $path.port }}*/}}
{{/*          {{- end }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}
{{/*{{- end }}*/}}

{{/*{{- if .Values.trembita_config.web_ui_access.ingress.enabled }}*/}}
{{/*apiVersion: networking.k8s.io/v1*/}}
{{/*kind: Ingress*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "trembita-1-22-6-ss.fullname" . }}-web*/}}
{{/*  annotations:*/}}
{{/*    {{- if .Values.trembita_config.web_ui_access.ingress.className }}*/}}
{{/*    kubernetes.io/ingress.class: {{ .Values.trembita_config.web_ui_access.ingress.className }}*/}}
{{/*    {{- end }}*/}}
{{/*spec:*/}}
{{/*  {{- if .Values.trembita_config.web_ui_access.ingress.tls }}*/}}
{{/*  tls:*/}}
{{/*    {{- range .Values.trembita_config.web_ui_access.ingress.tls }}*/}}
{{/*    - hosts:*/}}
{{/*        {{- range .hosts }}*/}}
{{/*        - {{ . }}*/}}
{{/*        {{- end }}*/}}
{{/*      secretName: {{ .secretName }}*/}}
{{/*    {{- end }}*/}}
{{/*  {{- end }}*/}}
{{/*  rules:*/}}
{{/*    {{- range .Values.trembita_config.web_ui_access.ingress.hosts }}*/}}
{{/*    - host: {{ .host }}*/}}
{{/*      http:*/}}
{{/*        paths:*/}}
{{/*          {{- range .paths }}*/}}
{{/*          - path: {{ .path }}*/}}
{{/*            pathType: {{ .pathType | default "Prefix" }}*/}}
{{/*            backend:*/}}
{{/*              service:*/}}
{{/*                name: {{ include "trembita-1-22-6-ss.fullname" $ }}-web*/}}
{{/*                port:*/}}
{{/*                  number: {{ .port }}*/}}
{{/*          {{- end }}*/}}
{{/*    {{- end }}*/}}
{{/*{{- end }}*/}}

