{{- with .Values.trembita_config.trembita_proxy_pod}}
{{- $ctx := . }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{.name}}
  labels:
    app: {{.name}}
spec:
  serviceName: {{ .name }}-secure-headless
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      name: {{.name}}
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: sidecar
          image: alpine/socat:1.8.0.0
          command: [ "sh", "-c", "
                       socat -d TCP-LISTEN:5577,bind=127.0.0.1,reuseaddr,fork TCP:{{$.Values.trembita_config.trembita_ocsp_cache_pod.name}}-service:6577 &
                       socat -d TCP-LISTEN:5766,bind=127.0.0.1,reuseaddr,fork TCP:{{$.Values.trembita_config.trembita_ocsp_cache_pod.name}}-admin-port-service:6766 &
                       socat -d TCP-LISTEN:2080,bind=127.0.0.1,reuseaddr,fork TCP:{{$.Values.trembita_config.trembita_monitor_pod.name}}-service-2080:2080 &
                       socat -d TCP-LISTEN:2082,bind=127.0.0.1,reuseaddr,fork TCP:{{$.Values.trembita_config.trembita_monitor_pod.name}}-service-2082:2082 &
                       socat -d TCP-LISTEN:5588,bind=127.0.0.1,reuseaddr,fork TCP:{{$.Values.trembita_config.trembita_monitor_pod.name}}-service-admin-port:5588
                     " ]
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 246Mi
        - name: {{.name}}
          image: {{.image}}
          imagePullPolicy: IfNotPresent
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 5500   {{/*External API port for connection between SEGs*/}}
            - containerPort: 80     {{/*Internal HTTP API port for internal connection clients*/}}
            - containerPort: 443    {{/*Internal HTTPS API port for connection between SEGs, not used in k8s*/}}
            - containerPort: 5566   {{/*Internal HTTP API port for admin porpuses, not used in k8s*/}}

          readinessProbe:
            exec:
              command:
                [ "/bin/trembita-healthcheck" ]
            timeoutSeconds: 20
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 1

          livenessProbe:
            exec:
              command:
                [ "/bin/trembita-healthcheck" ]
            timeoutSeconds: 20
            initialDelaySeconds: 20
            periodSeconds: 120
            failureThreshold: 10

          startupProbe:
            exec:
              command:
                - token-initializer
            timeoutSeconds: 1000000
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 1

          resources:
            requests:
              cpu: "1500m"       # garantee 1.5 core
              memory: "512Mi"   # garantee 512 МБ
            limits:
              cpu: "2000m"       # max 2 core
              memory: "1024Mi"     # max 1024 МБ
          command: [ "authbind", "java" ]
          args:
            - "-Xms150m"
            - "-Xmx512m"
            - "-Xshare:on"
            - "-XX:MaxMetaspaceSize=256m"
            - "-XX:+UseG1GC"
            - "-Dfile.encoding=UTF-8"
            - "-Dorg.bytedeco.javacpp.noPointerGC=true"
            - "-Dorg.bytedeco.javacpp.maxBytes=0"
            - "-Dorg.bytedeco.javacpp.maxPhysicalBytes=0"
            - "-Dorg.bytedeco.javacpp.cachedir=/tmp/bc_java/"
            - "-Djava.io.tmpdir=/tmp/bc_java"
            - "-Djava.library.path=/usr/share/uxp/lib/"
            - "-Dlogback.configurationFile=/app/proxy-logback.xml"
            - "-Duxp.proxy.clientHandlers=ee.cyber.uxp.proxy.clientproxy.MetadataHandler"
            - "-Duxp.proxy.serverServiceHandlers=ee.cyber.uxp.proxy.serverproxy.MetadataServiceSOAPHandlerImpl,ee.cyber.uxp.proxy.serverproxy.MonitoringServiceHandlerImpl"
            - "-Duxp.proxy.serverRestApiHandlers=ee.cyber.uxp.proxy.serverproxy.MetadataServiceRESTHandlerImpl"
            - "-cp"
            - "/app/proxy.jar:/app/jlib/signature-xades.jar:/app/jlib/addon/certprofile-trembita.jar:/app/jlib/addon/proxy/metaservice-1.22.7.jar:/app/jlib/addon/proxy/monitoring-1.22.7.jar:/app/jlib/addon/proxy/cipher-jce-provider-1.22.7.jar:/app/jlib/addon/proxy/ciplus-jce/*"
            - "ee.cyber.uxp.proxy.ProxyMain"

{{/*          securityContext:*/}}
{{/*            readOnlyRootFilesystem: true*/}}
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end}}
