{{- with .Values.trembita_config.secrets.identity_provider}}
  {{- if .enabled}}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    "helm.sh/hook": pre-install
{{/*    "helm.sh/hook-delete-policy": hook-succeeded*/}}
  name: {{ .name }}-init-secrets
spec:
  template:
    spec:
      serviceAccountName: {{ .name }}-init-sa
      restartPolicy: OnFailure
      containers:
        - name: generate-cert
          image: bitnami/kubectl:latest
          command:
            - /bin/sh
            - -c
            - |
              set -e

              ID=$(head /dev/urandom | tr -dc a-z0-9 | head -c 32)
              SECRET=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 64)

              echo "Generated ID: $ID"
              echo "Generated SECRET: $SECRET"

              echo "[identity-provider]" > /tmp/identity-provider.ini
              echo "security-server-client-id = $ID" >> /tmp/identity-provider.ini
              echo "security-server-client-secret = $SECRET" >> /tmp/identity-provider.ini

              kubectl create secret generic {{ .name }}-secret \
                --from-file=identity-provider.ini=/tmp/identity-provider.ini \
                --namespace={{ $.Release.Namespace }} \
                --dry-run=client -o yaml | kubectl apply -f -
{{- end}}
 {{- end}}