{{- with .Values.trembita_config.trembita_configuration_client_pod}}
{{- $ctx := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: sidecar
          image: alpine/socat
          command: [ "sh", "-c", "
            socat -d TCP-LISTEN:6666,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:5666
          " ]
          ports:
            - containerPort: 6577    {{/*OCSP port over socat proxy*/}}
            - containerPort: 6766    {{/*admin port over socat proxy*/}}
        - name: {{.name}}
          image: {{.image}}
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          ports:
            - containerPort: 5666 {{/*Admin port for imideatly download global config*/}}
          resources:
            requests:
              cpu: "100m"       # garantee 0.1 ядра
              memory: "256Mi"   # garantee 256 МБ
            limits:
              cpu: "200m"       # max 0.2 ядра
              memory: "512Mi"     # max 512 МБ
          livenessProbe:
            httpGet:
              path: /execute
              port: 6666
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
            successThreshold: 1
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              path: /execute
              port: 6666
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end}}