apiVersion: v1
kind: Service
metadata:
  name: {{ include "trembita-1.22.6-ss.fullname" . }}
  labels:
    {{- include "trembita-1.22.6-ss.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "trembita-1.22.6-ss.selectorLabels" . | nindent 4 }}
