{{- with .Values.trembita_config.trembita_postgresql_pod}}
apiVersion: v1
kind: Service
metadata:
  annotations:
{{/*    "helm.sh/hook": pre-install*/}}
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{.name}}
{{- end}}