{{- range $index, $cfg := .Values.trembita_config.trembita_postgresql_pod.persistentStorage}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
{{/*    "helm.sh/hook": pre-install*/}}
  name:  {{$cfg.name}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $cfg.size }}
  {{- if $cfg.storageClassName }}
  storageClassName: {{ $cfg.storageClassName }}
  {{- end }}
{{- end }}





{{/*{{- with .Values.trembita_config.trembita_postgresql_pod }}*/}}
{{/*apiVersion: v1*/}}
{{/*kind: PersistentVolumeClaim*/}}
{{/*metadata:*/}}
{{/*  annotations:*/}}
{{/*    "helm.sh/hook": pre-install*/}}
{{/*  name: {{.persistentStorage.}}-pvc*/}}
{{/*spec:*/}}
{{/*  accessModes:*/}}
{{/*    - ReadWriteOnce*/}}
{{/*  resources:*/}}
{{/*    requests:*/}}
{{/*      storage: {{ .Values.postgresql.persistence.size }}*/}}
{{/*  {{- if .Values.postgresql.persistence.storageClass}}*/}}
{{/*  storageClassName: {{ .Values.postgresql.persistence.storageClass }}*/}}
{{/*  {{- end }}*/}}
{{/*{{- end }}*/}}