apiVersion: v1
kind: Service
metadata:
  annotations:
{{/*    "helm.sh/hook": pre-install*/}}
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app: {{ include "trembita-1-22-6-ss.name" . }}-postgres