{{- range $index, $cfg := .Values.trembita_config.trembita_postgresql_pod.persistentStorage}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    "helm.sh/hook": pre-install
  name:  {{$cfg.name}}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $cfg.size }}
  {{- if $cfg.storageClassName }}
  storageClassName: {{ $cfg.storageClassName }}
  {{- end }}
{{- end }}