{{- with .Values.trembita_config.init_jobs.trembita_postgres}}
{{- $ctx := . }}
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
{{/*    "helm.sh/hook": pre-install*/}}
{{/*    "helm.sh/hook-delete-policy": hook-succeeded*/}}
  name: {{.name}}
  labels:
    app.kubernetes.io/name: {{ include "trembita-1-22-6-ss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{.name}}
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{.name}}
          image: {{.image}}
          imagePullPolicy: IfNotPresent
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: "100m"       # garantee 0.1 ядра
              memory: "256Mi"   # garantee 256 МБ
            limits:
              cpu: "200m"       # max 0.2 ядра
              memory: "512Mi"     # max 512 МБ
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end }}