{{- with .Values.trembita_config.trembita_monitor_pod}}
{{- $ctx := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
  labels:
    app: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      name: {{.name}}
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: sidecar
          image: alpine/socat
          command: [ "sh", "-c", "
            socat -d TCP-LISTEN:5577,bind=127.0.0.1,reuseaddr,fork TCP:{{ $.Values.trembita_config.trembita_ocsp_cache_pod.name}}-service:6577 &
            socat -d TCP-LISTEN:3080,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:2080 &
            socat -d TCP-LISTEN:3082,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:2082 &
            socat -d TCP-LISTEN:6588,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:5588
          " ]
          ports:
            - containerPort: 2080    {{/**/}}
            - containerPort: 2082    {{/**/}}
            - containerPort: 5588    {{/**/}}
        - name: {{.name}}
          image: {{.image}}
          imagePullPolicy: IfNotPresent
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: "100m"       # garantee 0.1 ядра
              memory: "256Mi"   # garantee 256 МБ
            limits:
              cpu: "200m"       # max 0.2 ядра
              memory: "512Mi"     # max 512 МБ
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end}}
