{{- with .Values.trembita_config.trembita_monitor_pod}}
{{- $ctx := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.name}}
  labels:
    app: {{.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.name}}
  template:
    metadata:
      name: {{.name}}
      labels:
        app: {{.name}}
    spec:
      containers:
        - name: socat
          image: alpine/socat:1.8.0.1
          command: [ "sh", "-c", "
                      socat -d -d -d TCP-LISTEN:5577,bind=127.0.0.1,reuseaddr,fork TCP:{{ $.Values.trembita_config.trembita_ocsp_cache_pod.name}}-service:6577 &
                    " ]
        - name: nginx_proxy
          image: kshypachov/trembita_monitor_sidecar_nginx:v1.0.0
{{/*          command: [ "sh", "-c", "*/}}
{{/*            socat -d -d -d TCP-LISTEN:5577,bind=127.0.0.1,reuseaddr,fork TCP:{{ $.Values.trembita_config.trembita_ocsp_cache_pod.name}}-service:6577 &*/}}
{{/*            socat -d -d -d TCP-LISTEN:3080,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:2080 &*/}}
{{/*            socat -d -d -d TCP-LISTEN:3082,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:2082 &*/}}
{{/*            socat -d -d -d TCP-LISTEN:6588,bind=0.0.0.0,reuseaddr,fork TCP:127.0.0.1:5588*/}}
{{/*          " ]*/}}
          ports:
            - containerPort: 2080    {{/**/}}
            - containerPort: 2082    {{/**/}}
            - containerPort: 5588    {{/**/}}
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 400m
              memory: 246Mi
        - name: {{.name}}
          image: {{.image}}
          imagePullPolicy: IfNotPresent
          {{if .env}}
          env:
            {{- range $k, $v := .env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- end }}
          resources:
            requests:
              cpu: "400m"       # garantee 0.1 ядра
              memory: "320Mi"   # garantee 256 МБ
            limits:
              cpu: "500m"       # max 0.2 ядра
              memory: "620Mi"     # max 512 МБ
          command: [ "/opt/java/openjdk/bin/java" ]
          args:
            - "-Xms50m"
            - "-Xmx256m"
            - "-XX:MaxMetaspaceSize=128m"
            - "-XX:+UseG1GC"
            - "-Xshare:on"
            - "-Dfile.encoding=UTF-8"
            - "-Djava.library.path=/usr/share/uxp/lib/"
            - "-Dorg.bytedeco.javacpp.cachedir=/tmp/bc_java/"
            - "-Dorg.bytedeco.javacpp.noPointerGC=true"
            - "-Dorg.bytedeco.javacpp.maxBytes=0"
            - "-Dorg.bytedeco.javacpp.maxPhysicalBytes=0"
            - "-Duxp.common.temp-files-path=/tmp/java/"
            - "-Duxp.center.allowed-certificate-profiles=ee.cyber.uxp.common.certificateprofile.ua.UaCertificateProfileInfoProvider"
            - "-Duxp.common.license-file=/etc/uxp/license.lic"
            - "-Dlogback.configurationFile=/app/proxy-monitor-agent-logback.xml"
            - "-Duxp.proxy-monitoring-agent.monitor-agent-conf-file=/app/monitor-agent.ini"
            - "-Duser.country=UA"
            - "-Duxp.proxy-monitoring-agent.admin-port=4588"
            - "-Duxp.status-service.listen-port=1082"
            - "-Duxp.proxy-monitoring-agent.port=1080"
            - "-Duxp.common.temp-files-path=/etc/uxp/tmp/"
            - "-Dorg.bytedeco.javacpp.maxPhysicalBytes=0"
            - "-cp"
            - "/app/jlib/monitoring-proxy-agent.jar:/app/jlib/signature-xades.jar:/app/jlib/addon/proxy/cipher-jce-provider-1.22.7.jar:/app/jlib/addon/proxy/ciplus-jce/*"
            - "ee.cyber.uxp.proxymonitoragent.ProxyMonitorAgentMain"
          securityContext:
            readOnlyRootFilesystem: true
{{- template "trembita.volumeMountsAndCM" (dict "ctx" . "root" $) }}
{{- end}}
